### ISSUE TITLE
Context Menu

### ISSUE THREAD

**Issue by greenpdx** [fibo/three-orbitcontrols#2]
I am using vue framework (vuejs.org) and have componentized threejs. The problem I am having is I get no click events in the framework and I do not want to add addEventListener() functions.  Is there a way to have a contextmenu event to bubble up or call a callback function.  I am sorry but my knowledge in Vue internals is limited.  
You can look at the code on github greenpdx/vue3d.

**Comment by fibo** [comment]
Hi @greenpdx I tryed to run your project. At first the `npm run dev` got an error, then I had to install *axios* and it started (only on http://localhost:8080, not on https://localhost:8080).

At the end I could run your page, and I found an error that seems related to Vue (see screenshot below).

I cannot help here, I am sorry but I don't know Vue: I have a project where I used `three-orbitcontrols` with React and prolly it should work everywhere since it just defines event listeners in the canvas, so it should play well with others.

Good luck!

<img width="1252" alt="screen shot 2017-08-06 at 16 05 56" src="https://user-images.githubusercontent.com/176730/29004047-ce290ccc-7ac1-11e7-8135-4a4f3d174ada.png">
